import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import * as z from "zod";
import { readFile, writeFile, unlink, mkdir } from "node:fs/promises";
import { join, normalize, dirname } from "node:path";
import { REPO_ROOT } from "../utils/fs.js";

/** Top-level directories that must never be written into.
 * node_modules: third-party packages managed by bun/npm.
 * .git: version-control internals.
 * dist: compiled build output — always regenerated by `bun run build`.
 */
const BLOCKED_DIRS = new Set(["node_modules", ".git", "dist"]);

/**
 * Normalise a repo-relative path and return its absolute equivalent.
 * Returns null if the path is absolute, contains traversal sequences (`..`),
 * or lands in a blocked directory.
 */
function resolveRepoPath(relPath: string): string | null {
  const normalized = normalize(relPath);
  // Reject absolute paths and any path that resolves up out of the root
  if (normalized.startsWith("/") || normalized.startsWith("..")) return null;
  const abs = join(REPO_ROOT, normalized);
  // Belt-and-suspenders: ensure we stayed inside the repo
  if (!abs.startsWith(REPO_ROOT + "/") && abs !== REPO_ROOT) return null;
  // Prevent writes into blocked top-level dirs
  const topDir = normalized.split("/")[0];
  if (BLOCKED_DIRS.has(topDir)) return null;
  return abs;
}

/**
 * Files that must never be deleted to keep the server operational.
 * The agent can still edit them via edit_file.
 */
const DELETE_BLOCKLIST = new Set([
  "package.json",
  "tsconfig.json",
  "src/server.ts",
]);

/** Register write tools onto the server. */
export function registerWriteTools(server: McpServer): void {
  // ── write_file ──────────────────────────────────────────────────────────────
  server.registerTool(
    "write_file",
    {
      description:
        "Create or overwrite a file at a repo-relative path with the given text content. " +
        "Parent directories are created automatically. " +
        "Rejects paths that escape the repo root or target node_modules, .git, or dist. " +
        "Use this tool to make code changes in the local clone; use GitHub MCP tools " +
        "(e.g. create_pull_request, report_progress) for remote git operations. " +
        "Pass dryRun: true to validate the path without writing anything.",
      inputSchema: {
        path: z.string().describe("Repo-relative path, e.g. src/tools/example.ts"),
        content: z.string().describe("Full text content to write to the file."),
        dryRun: z
          .boolean()
          .optional()
          .describe(
            "When true, resolves and validates the path but does not write anything."
          ),
      },
      annotations: { readOnlyHint: false, destructiveHint: true },
    },
    async ({ path, content, dryRun }) => {
      const abs = resolveRepoPath(path);
      if (!abs) {
        return {
          isError: true,
          content: [
            {
              type: "text",
              text: `Rejected: path "${path}" escapes the repo root or targets a blocked directory.`,
            },
          ],
        };
      }
      if (dryRun) {
        return {
          content: [
            {
              type: "text",
              text: `Dry run: would write ${content.length} bytes to ${path}`,
            },
          ],
        };
      }
      await mkdir(dirname(abs), { recursive: true });
      await writeFile(abs, content, "utf-8");
      return {
        content: [{ type: "text", text: `✅ Wrote ${content.length} bytes to ${path}` }],
      };
    }
  );

  // ── edit_file ───────────────────────────────────────────────────────────────
  server.registerTool(
    "edit_file",
    {
      description:
        "Find and replace exactly one occurrence of old_str with new_str in a file. " +
        "Fails if old_str is not found or matches more than once (safe by design — " +
        "add more context to make the match unique). " +
        "Use this for surgical edits to existing files; use write_file for full rewrites.",
      inputSchema: {
        path: z.string().describe("Repo-relative path to the file to edit."),
        old_str: z.string().describe("Exact string to find. Must match exactly once."),
        new_str: z.string().describe("Replacement string."),
      },
      annotations: { readOnlyHint: false, destructiveHint: true },
    },
    async ({ path, old_str, new_str }) => {
      const abs = resolveRepoPath(path);
      if (!abs) {
        return {
          isError: true,
          content: [
            {
              type: "text",
              text: `Rejected: path "${path}" escapes the repo root or targets a blocked directory.`,
            },
          ],
        };
      }

      let current: string;
      try {
        current = await readFile(abs, "utf-8");
      } catch {
        return {
          isError: true,
          content: [{ type: "text", text: `File not found: ${path}` }],
        };
      }

      const occurrences = current.split(old_str).length - 1;
      if (occurrences === 0) {
        return {
          isError: true,
          content: [{ type: "text", text: "String not found" }],
        };
      }
      if (occurrences > 1) {
        return {
          isError: true,
          content: [
            {
              type: "text",
              text: `String matches ${occurrences} occurrences — add more context to make it unique.`,
            },
          ],
        };
      }

      const updated = current.replace(old_str, new_str);
      await writeFile(abs, updated, "utf-8");
      return {
        content: [{ type: "text", text: `✅ Edited ${path}` }],
      };
    }
  );

  // ── delete_file ─────────────────────────────────────────────────────────────
  server.registerTool(
    "delete_file",
    {
      description:
        "Permanently delete a single file from the repo. " +
        "Rejects paths outside the repo root, blocked directories, and a small set " +
        "of critical files (package.json, tsconfig.json, src/server.ts). " +
        "Pass dryRun: true to validate the path without deleting anything.",
      inputSchema: {
        path: z.string().describe("Repo-relative path to the file to delete."),
        dryRun: z
          .boolean()
          .optional()
          .describe(
            "When true, resolves and validates the path but does not delete anything."
          ),
      },
      annotations: { readOnlyHint: false, destructiveHint: true },
    },
    async ({ path, dryRun }) => {
      const normalized = normalize(path);

      if (DELETE_BLOCKLIST.has(normalized)) {
        return {
          isError: true,
          content: [
            {
              type: "text",
              text: `Rejected: "${path}" is a critical file and cannot be deleted.`,
            },
          ],
        };
      }

      const abs = resolveRepoPath(path);
      if (!abs) {
        return {
          isError: true,
          content: [
            {
              type: "text",
              text: `Rejected: path "${path}" escapes the repo root or targets a blocked directory.`,
            },
          ],
        };
      }

      if (dryRun) {
        return {
          content: [
            {
              type: "text",
              text: `Dry run: would delete ${path}`,
            },
          ],
        };
      }

      try {
        await unlink(abs);
      } catch {
        return {
          isError: true,
          content: [{ type: "text", text: `File not found or could not be deleted: ${path}` }],
        };
      }

      return {
        content: [{ type: "text", text: `✅ Deleted ${path}` }],
      };
    }
  );
}
